/**
 * Geometry of public/story/story-atlas.png.
 *
 * Generated by scripts/generate-story-frames.mjs — rerun it after changing the
 * artwork rather than editing these values by hand.
 */
export const STORY_ATLAS = {
  src: "/story/story-atlas.png",
  /** Half-resolution sheet, for small screens. Same grid, same frame count. */
  srcSmall: "/story/story-atlas-half.png",
  columns: 8,
  rows: 12,
  frameCount: 96,
  frameWidth: 480,
  frameHeight: 270,
} as const;
