/**
 * Geometry of public/duel/duel-sheet.png.
 *
 * Generated by scripts/generate-duel-frames.mjs — rerun it after changing the
 * artwork rather than editing these values by hand.
 */
export const DUEL_SHEET = {
  src: "/duel/duel-sheet.png",
  /** Quarter-weight sheet, for small screens. Same grid, same frame count. */
  srcSmall: "/duel/duel-sheet-half.png",
  columns: 8,
  rows: 6,
  frameCount: 48,
  frameWidth: 560,
  frameHeight: 245,
  /** 14 frames a second: fast enough to land a hit, slow enough to follow. */
  durationMs: 3429,
} as const;
