import { randomBytes } from "node:crypto";
import { mkdirSync } from "node:fs";
import { readFile, unlink, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { ACCEPTED_MIME, EXTENSION, MAX_BYTES, sniffFormat, type ImageFormat } from "./formats";
import { stripMetadata } from "./strip";

/**
 * Exhibits live on disk, never in the database.
 *
 * Their own directory, mounted as its own volume, so a restore can bring back
 * the ledger and the plates together — a case whose exhibits are gone is a
 * case nobody can re-read.
 */
const EVIDENCE_DIR = process.env.BANK_EVIDENCE_DIR ?? "evidence";

/*
 * The paths below carry `turbopackIgnore` comments. Next traces filesystem
 * calls at build time to work out which files to copy into the standalone
 * output, and a path it cannot evaluate statically makes it copy a directory
 * defensively. This directory is a runtime mount that holds no build output at
 * all, so there is nothing to trace and telling the tracer so keeps the image
 * from swallowing the repository.
 */

export type StoredExhibit = { filename: string; mime: string; bytes: number };

export type AcceptResult =
  | { ok: true; exhibit: StoredExhibit }
  | { ok: false; message: string };

/**
 * Takes an upload, keeps the picture, and throws the rest away.
 *
 * The stored name is generated rather than taken from the upload: an original
 * filename is attacker-controlled, and it is also frequently
 * `IMG_20260825_London_Arjun.jpg`, which leaks the same things the Exif does.
 */
export async function acceptExhibit(file: File): Promise<AcceptResult> {
  if (file.size === 0) return { ok: false, message: "That file is empty." };
  if (file.size > MAX_BYTES) {
    return { ok: false, message: "An exhibit may not exceed 5 MB." };
  }

  const original = new Uint8Array(await file.arrayBuffer());
  const format = sniffFormat(original);
  if (!format) {
    return { ok: false, message: "An exhibit must be a PNG, JPEG, or WebP image." };
  }

  const cleaned = stripMetadata(original, format);
  const filename = generatedName(format);

  mkdirSync(/*turbopackIgnore: true*/ EVIDENCE_DIR, { recursive: true });
  await writeFile(/*turbopackIgnore: true*/ exhibitPath(filename), cleaned, { flag: "wx" });

  return {
    ok: true,
    exhibit: { filename, mime: ACCEPTED_MIME[format], bytes: cleaned.length },
  };
}

function generatedName(format: ImageFormat): string {
  return `${randomBytes(16).toString("hex")}${EXTENSION[format]}`;
}

/**
 * Resolves a stored name to a path, refusing anything that is not one.
 *
 * The name in the database was generated by `generatedName`, so it can only
 * ever match this shape. Checking it again here means a hand-edited row or a
 * crafted URL cannot walk out of the evidence directory.
 */
export function exhibitPath(filename: string): string {
  if (!/^[0-9a-f]{32}\.(png|jpg|webp)$/.test(filename)) {
    throw new Error("Not an exhibit filename");
  }
  return join(resolve(/*turbopackIgnore: true*/ EVIDENCE_DIR), filename);
}

export async function readExhibit(filename: string): Promise<Buffer> {
  return readFile(/*turbopackIgnore: true*/ exhibitPath(filename));
}

/** Used to clean up plates whose case failed to file. */
export async function discardExhibit(filename: string): Promise<void> {
  await unlink(/*turbopackIgnore: true*/ exhibitPath(filename)).catch(() => {});
}
